### ISSUE TITLE
TypeError: NoneType object is not iterable

### ISSUE THREAD

**Issue by GertjanBrouwer** [EnriqueMoran/lumberjackBot#1]
I get this error: 

Traceback (most recent call last):
  File "lumperjack.py", line 64, in <module>
    playX, playY = pyautogui.locateCenterOnScreen('playButton.png')
TypeError: 'NoneType' object is not iterable

Any idea how to fix this issue??

**Comment by EnriqueMoran** [comment]
It seems the error is due to "playButton.png" image is not being recognized. 
This may happen when the graphics of the game get updated (and changed), in order to fix the error just take a screenshot of a portion of  the play button and replace it for the old one.
The new image must be one with nothing else but a flat color background (as the old image is), because the "start game" button and "restart game" isn't the same (only the background color is).

The play and replay buttons are different:

![](https://i.gyazo.com/abe3ec8230eb4a7d6e9a838093fd5dab.png)   ![](https://i.gyazo.com/e1e0b40ddb398255555b5a9e1f2933a9.png)


A good "playButton" image could be the following one, because its the same for each button. So you can download this one and replace it for the old image:

![](https://i.gyazo.com/a61ea542d2ba1a130978f99896d9fb96.png)
